<a href="https://colab.research.google.com/github/sahanediriweera/advancedPytorch/blob/main/Pytorch_Advacned_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'1.13.0+cu116'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor(
    [
        [7,10],
        [10,2]
    ]
)
MATRIX

tensor([[ 7, 10],
        [10,  2]])

In [10]:
tensor = torch.tensor([
    [7,5,6],
    [8,5,3,],
    [7,5,3]
])
tensor

tensor([[7, 5, 6],
        [8, 5, 3],
        [7, 5, 3]])

In [14]:
TENSOR = torch.tensor([[
                        [7,8,5],
                        [1,5,9],
                        [4,7,3]]])

In [12]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.8609, 0.1907, 0.9918, 0.1106],
         [0.1450, 0.2527, 0.0897, 0.9047],
         [0.6607, 0.0921, 0.9720, 0.7817]]), torch.float32)

In [17]:
random_image_size_tensor = torch.rand(size=(224,224,33))
random_image_size_tensor, random_image_size_tensor.dtype

(tensor([[[0.0156, 0.9081, 0.0423,  ..., 0.2486, 0.8264, 0.1123],
          [0.1225, 0.8074, 0.5984,  ..., 0.6060, 0.6081, 0.3754],
          [0.5195, 0.6024, 0.9286,  ..., 0.2569, 0.3361, 0.2269],
          ...,
          [0.9310, 0.4473, 0.2186,  ..., 0.4932, 0.7176, 0.3699],
          [0.7405, 0.1565, 0.2818,  ..., 0.3729, 0.0982, 0.8156],
          [0.2944, 0.7152, 0.3363,  ..., 0.5324, 0.1865, 0.8472]],
 
         [[0.8262, 0.2876, 0.0317,  ..., 0.6327, 0.9328, 0.3712],
          [0.5042, 0.3230, 0.1632,  ..., 0.1338, 0.1229, 0.9203],
          [0.3514, 0.2055, 0.7041,  ..., 0.3881, 0.4897, 0.4241],
          ...,
          [0.7415, 0.0761, 0.0953,  ..., 0.4833, 0.6822, 0.1234],
          [0.0351, 0.6045, 0.1385,  ..., 0.4307, 0.5705, 0.7656],
          [0.3513, 0.3289, 0.6061,  ..., 0.6498, 0.4724, 0.4385]],
 
         [[0.8708, 0.4793, 0.7761,  ..., 0.7810, 0.5484, 0.6877],
          [0.3757, 0.2198, 0.7985,  ..., 0.8387, 0.4372, 0.8352],
          [0.9977, 0.7569, 0.4127,  ...,

In [18]:
zeros = torch.zeros(size = (224,224,3))
zeros, zeros.dtype

(tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         ...,
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]), torch.float3

In [19]:
ones = torch.ones(size = (224,224,3))
ones, ones.dtype

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         ...,
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]), torch.float3

In [22]:
zero_to_ten = torch.arange(start = 0,end = 10,step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
ten_zeros_like = torch.zeros_like(input = zero_to_ten)
ten_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])