<a href="https://colab.research.google.com/github/sahanediriweera/advancedPytorch/blob/main/Pytorch_Advacned_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'1.13.0+cu116'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor(
    [
        [7,10],
        [10,2]
    ]
)
MATRIX

tensor([[ 7, 10],
        [10,  2]])

In [10]:
tensor = torch.tensor([
    [7,5,6],
    [8,5,3,],
    [7,5,3]
])
tensor

tensor([[7, 5, 6],
        [8, 5, 3],
        [7, 5, 3]])

In [14]:
TENSOR = torch.tensor([[
                        [7,8,5],
                        [1,5,9],
                        [4,7,3]]])

In [12]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])