<a href="https://colab.research.google.com/github/sahanediriweera/advancedPytorch/blob/main/Pytorch_Advacned_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'1.13.1+cu116'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor(
    [
        [7,10],
        [10,2]
    ]
)
MATRIX

tensor([[ 7, 10],
        [10,  2]])

In [9]:
tensor = torch.tensor([
    [7,5,6],
    [8,5,3,],
    [7,5,3]
])
tensor

tensor([[7, 5, 6],
        [8, 5, 3],
        [7, 5, 3]])

In [10]:
TENSOR = torch.tensor([[
                        [7,8,5],
                        [1,5,9],
                        [4,7,3]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.1666, 0.0592, 0.6235, 0.5974],
         [0.1226, 0.1211, 0.4415, 0.5985],
         [0.7088, 0.4920, 0.6292, 0.4431]]), torch.float32)

In [14]:
random_image_size_tensor = torch.rand(size=(224,224,33))
random_image_size_tensor, random_image_size_tensor.dtype

(tensor([[[9.7423e-01, 7.8832e-01, 6.8238e-01,  ..., 6.7981e-01,
           4.0531e-01, 3.3920e-01],
          [6.6639e-01, 4.7433e-01, 8.7675e-01,  ..., 8.8675e-02,
           8.2285e-01, 3.1203e-01],
          [1.9384e-01, 5.1993e-02, 3.7524e-01,  ..., 4.9082e-02,
           1.6351e-01, 6.5129e-01],
          ...,
          [9.4487e-01, 8.7310e-01, 5.7012e-01,  ..., 2.7656e-01,
           6.4755e-01, 9.8880e-01],
          [9.7728e-01, 6.0544e-01, 6.0734e-01,  ..., 1.9941e-01,
           5.1668e-01, 6.7203e-01],
          [7.4883e-01, 7.3543e-01, 8.8841e-01,  ..., 8.2778e-01,
           1.9318e-01, 3.0338e-01]],
 
         [[1.7315e-01, 7.8370e-01, 6.4189e-01,  ..., 1.1707e-01,
           5.9972e-01, 9.8011e-01],
          [5.2262e-02, 5.6318e-01, 9.3476e-01,  ..., 1.8981e-01,
           9.1142e-01, 2.2175e-02],
          [7.6835e-01, 3.2948e-01, 7.6888e-01,  ..., 7.5329e-01,
           3.3948e-01, 2.7292e-01],
          ...,
          [7.9135e-02, 9.4033e-01, 5.2930e-01,  ..., 9.955

In [15]:
zeros = torch.zeros(size = (224,224,3))
zeros, zeros.dtype

(tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         ...,
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]), torch.float3

In [16]:
ones = torch.ones(size = (224,224,3))
ones, ones.dtype

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         ...,
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]), torch.float3

In [17]:
zero_to_ten = torch.arange(start = 0,end = 10,step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
ten_zeros_like = torch.zeros_like(input = zero_to_ten)
ten_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],device=None,dtype=None,requires_grad=False)
float_32_tensor , float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [20]:
float_16_tensor = torch.tensor([3.0,6.,9.0],dtype = torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [21]:
some_tensor = torch.rand(size = (3,4))

print(some_tensor)
print(f"The device type of the tensor is {some_tensor.device}")
print(f"The dtype of the tensor is {some_tensor.dtype}")
print(f"The shape of the tensor is {some_tensor.shape}")

tensor([[0.2080, 0.6761, 0.2948, 0.0507],
        [0.6116, 0.3612, 0.1766, 0.3180],
        [0.5817, 0.5122, 0.2423, 0.1905]])
The device type of the tensor is cpu
The dtype of the tensor is torch.float32
The shape of the tensor is torch.Size([3, 4])


In [22]:
tensor = torch.tensor([2.0,7.0,1.0])
tensor

tensor([2., 7., 1.])

In [23]:
tensor+1

tensor([3., 8., 2.])

In [24]:
tensor*10

tensor([20., 70., 10.])

In [25]:
tensor/5

tensor([0.4000, 1.4000, 0.2000])

In [26]:
torch.multiply(tensor,50)

tensor([100., 350.,  50.])

In [27]:
torch.add(tensor,4)

tensor([ 6., 11.,  5.])

In [28]:
print(f"{tensor}*{tensor}")
print(torch.mul(tensor,tensor))

tensor([2., 7., 1.])*tensor([2., 7., 1.])
tensor([ 4., 49.,  1.])


In [29]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [30]:
torch.matmul(tensor,tensor)

tensor(14)

In [31]:
tensor_A = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])

In [32]:
tensor_B = torch.tensor([[5,6],
                         [7,2],
                         [3,9]])

In [33]:
#torch.matmul(tensor_A,tensor_B)

RuntimeError: ignored

In [34]:
tensor_A.T

tensor([[1, 2, 3],
        [2, 3, 4]])

In [35]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[17, 11, 21],
        [28, 20, 33],
        [39, 29, 45]])

In [36]:
print(f"The Original shape is {tensor_A.shape} and the transformed shape is {tensor_A.T.shape}")

The Original shape is torch.Size([3, 2]) and the transformed shape is torch.Size([2, 3])


In [37]:
torch.mm(tensor_A,tensor_A.T)

tensor([[ 5,  8, 11],
        [ 8, 13, 18],
        [11, 18, 25]])

In [40]:
torch.manual_seed(42)

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

linear = torch.nn.Linear(
    in_features = 2,
    out_features = 6
)

x = tensor_A

output = linear(x)

print(x.shape, tensor_A.shape)

print(output, output.shape)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>) torch.Size([3, 6])
