<a href="https://colab.research.google.com/github/sahanediriweera/advancedPytorch/blob/main/Pytorch_Advacned_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch
torch.__version__

'1.13.1+cu116'

In [22]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [23]:
scalar.ndim

0

In [24]:
scalar.item()

7

In [25]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [26]:
vector.ndim

1

In [27]:
vector.shape

torch.Size([2])

In [28]:
MATRIX = torch.tensor(
    [
        [7,10],
        [10,2]
    ]
)
MATRIX

tensor([[ 7, 10],
        [10,  2]])

In [29]:
tensor = torch.tensor([
    [7,5,6],
    [8,5,3,],
    [7,5,3]
])
tensor

tensor([[7, 5, 6],
        [8, 5, 3],
        [7, 5, 3]])

In [30]:
TENSOR = torch.tensor([[
                        [7,8,5],
                        [1,5,9],
                        [4,7,3]]])

In [31]:
TENSOR.ndim

3

In [32]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.7055, 0.8310, 0.1013, 0.6094],
         [0.0175, 0.0891, 0.0530, 0.0450],
         [0.3327, 0.3790, 0.3994, 0.4603]]), torch.float32)

In [34]:
random_image_size_tensor = torch.rand(size=(224,224,33))
random_image_size_tensor, random_image_size_tensor.dtype

(tensor([[[0.4708, 0.4304, 0.9254,  ..., 0.9263, 0.3512, 0.9781],
          [0.2944, 0.3854, 0.4171,  ..., 0.7573, 0.1149, 0.8363],
          [0.7722, 0.7770, 0.5786,  ..., 0.0629, 0.6459, 0.4011],
          ...,
          [0.5571, 0.3861, 0.0441,  ..., 0.5640, 0.7744, 0.7411],
          [0.3133, 0.9749, 0.9366,  ..., 0.1762, 0.6639, 0.4291],
          [0.9634, 0.3486, 0.4802,  ..., 0.1448, 0.3016, 0.4226]],
 
         [[0.6079, 0.0705, 0.0079,  ..., 0.9134, 0.5375, 0.4339],
          [0.6070, 0.4697, 0.8567,  ..., 0.6311, 0.2122, 0.8867],
          [0.6890, 0.5222, 0.9369,  ..., 0.8804, 0.4838, 0.7637],
          ...,
          [0.4180, 0.2781, 0.7998,  ..., 0.5191, 0.8272, 0.5086],
          [0.5555, 0.1248, 0.9527,  ..., 0.4497, 0.2065, 0.5525],
          [0.3316, 0.3807, 0.4752,  ..., 0.0115, 0.0418, 0.8949]],
 
         [[0.8449, 0.6974, 0.6810,  ..., 0.5829, 0.8896, 0.2632],
          [0.9371, 0.1533, 0.6391,  ..., 0.0906, 0.1573, 0.7161],
          [0.7147, 0.6644, 0.8001,  ...,

In [35]:
zeros = torch.zeros(size = (224,224,3))
zeros, zeros.dtype

(tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         ...,
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]), torch.float3

In [36]:
ones = torch.ones(size = (224,224,3))
ones, ones.dtype

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         ...,
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]), torch.float3

In [37]:
zero_to_ten = torch.arange(start = 0,end = 10,step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
ten_zeros_like = torch.zeros_like(input = zero_to_ten)
ten_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],device=None,dtype=None,requires_grad=False)
float_32_tensor , float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [40]:
float_16_tensor = torch.tensor([3.0,6.,9.0],dtype = torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [41]:
some_tensor = torch.rand(size = (3,4))

print(some_tensor)
print(f"The device type of the tensor is {some_tensor.device}")
print(f"The dtype of the tensor is {some_tensor.dtype}")
print(f"The shape of the tensor is {some_tensor.shape}")

tensor([[0.1262, 0.1819, 0.1269, 0.6382],
        [0.7368, 0.6414, 0.4999, 0.0719],
        [0.2859, 0.5750, 0.0540, 0.7716]])
The device type of the tensor is cpu
The dtype of the tensor is torch.float32
The shape of the tensor is torch.Size([3, 4])


In [42]:
tensor = torch.tensor([2.0,7.0,1.0])
tensor

tensor([2., 7., 1.])

In [43]:
tensor+1

tensor([3., 8., 2.])

In [44]:
tensor*10

tensor([20., 70., 10.])

In [45]:
tensor/5

tensor([0.4000, 1.4000, 0.2000])

In [46]:
torch.multiply(tensor,50)

tensor([100., 350.,  50.])

In [47]:
torch.add(tensor,4)

tensor([ 6., 11.,  5.])

In [48]:
print(f"{tensor}*{tensor}")
print(torch.mul(tensor,tensor))

tensor([2., 7., 1.])*tensor([2., 7., 1.])
tensor([ 4., 49.,  1.])


In [49]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [50]:
torch.matmul(tensor,tensor)

tensor(14)

In [51]:
tensor_A = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])

In [52]:
tensor_B = torch.tensor([[5,6],
                         [7,2],
                         [3,9]])

In [53]:
#torch.matmul(tensor_A,tensor_B)

In [54]:
tensor_A.T

tensor([[1, 2, 3],
        [2, 3, 4]])

In [55]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[17, 11, 21],
        [28, 20, 33],
        [39, 29, 45]])

In [56]:
print(f"The Original shape is {tensor_A.shape} and the transformed shape is {tensor_A.T.shape}")

The Original shape is torch.Size([3, 2]) and the transformed shape is torch.Size([2, 3])


In [57]:
torch.mm(tensor_A,tensor_A.T)

tensor([[ 5,  8, 11],
        [ 8, 13, 18],
        [11, 18, 25]])

In [58]:
torch.manual_seed(42)

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

linear = torch.nn.Linear(
    in_features = 2,
    out_features = 6
)

x = tensor_A

output = linear(x)

print(x.shape, tensor_A.shape)

print(output, output.shape)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>) torch.Size([3, 6])


In [59]:
import torch
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
print(f"Maximum {x.max()}")
print(f"Minimum {x.min()}")
print(f"Mean {x.type(torch.float32).mean()}")
print(f"Sum {x.sum()}")

Maximum 90
Minimum 0
Mean 45.0
Sum 450


In [61]:
tensor_c = torch.arange(10,100,10)

print(f"tensor {tensor_c}")

print(f"tensor argmax {tensor_c.argmax()}")
print(f"tensor argmin {tensor_c.argmin()}")

tensor tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor argmax 8
tensor argmin 0


In [62]:
tensor_d = torch.arange(10.,100.,10.)
tensor_d.dtype

torch.float32

In [63]:
tensor_f = torch.arange(1.,8.)
tensor_f, tensor_f.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [64]:
tensor_f_reshaped = tensor_f.reshape(1,7)
tensor_f_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [65]:
z = tensor_f.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [66]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]),
 tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [67]:
f_stacked = torch.stack([tensor_f,tensor_f,tensor_f,tensor_f])
f_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [68]:
print(f"f reshaped {tensor_f_reshaped}")
print(f"F reshaped shape {tensor_f_reshaped.shape}")

f reshaped tensor([[5., 2., 3., 4., 5., 6., 7.]])
F reshaped shape torch.Size([1, 7])


In [69]:
tensor_f_squeezed = tensor_f.squeeze()
tensor_f_squeezed, tensor_f_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [70]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_permuted , x_permuted.shape

(tensor([[[0.2666, 0.4414, 0.1053,  ..., 0.5697, 0.3397, 0.3421],
          [0.6576, 0.9902, 0.9008,  ..., 0.5322, 0.1844, 0.3568],
          [0.0231, 0.0614, 0.9203,  ..., 0.4989, 0.6272, 0.8345],
          ...,
          [0.3599, 0.5387, 0.5521,  ..., 0.1790, 0.9871, 0.1551],
          [0.7442, 0.6381, 0.6170,  ..., 0.3450, 0.9618, 0.6393],
          [0.1369, 0.6237, 0.2424,  ..., 0.1167, 0.2933, 0.0992]],
 
         [[0.6274, 0.2969, 0.2695,  ..., 0.2088, 0.9565, 0.0172],
          [0.9813, 0.5978, 0.9180,  ..., 0.8510, 0.8533, 0.1704],
          [0.6317, 0.1727, 0.9251,  ..., 0.0933, 0.5955, 0.2273],
          ...,
          [0.1989, 0.1378, 0.6004,  ..., 0.9954, 0.5877, 0.7881],
          [0.8621, 0.0106, 0.3402,  ..., 0.6359, 0.7925, 0.7158],
          [0.4302, 0.8480, 0.8264,  ..., 0.1133, 0.5889, 0.3078]],
 
         [[0.2696, 0.8317, 0.3588,  ..., 0.6539, 0.0660, 0.3031],
          [0.5840, 0.7888, 0.2201,  ..., 0.4556, 0.5698, 0.6172],
          [0.7472, 0.1405, 0.5313,  ...,

In [72]:
tensor_g = torch.arange(1,10).reshape(1,3,3)
tensor_g , tensor_g.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [73]:
tensor_g[:,0]

tensor([[1, 2, 3]])

In [74]:
tensor_g[:,:,0]

tensor([[1, 4, 7]])

In [75]:
tensor_g[:,:,1]

tensor([[2, 5, 8]])

In [77]:
tensor_g[:,1,1]

tensor([5])

In [81]:
import numpy as np
array = np.arange(1,8)
tensor_h = torch.from_numpy(array)
array, tensor_h

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [83]:
import torch
import random

RANDOM_SEED = 42

torch.manual_seed(seed = RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

random_tensor_C == random_tensor_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Next part is the use of cuda cores or GPUs for machine learning